
openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Jorrit05/DevOpsAssignmentOne/1.0.0
info:
  description: This is a simple API
  version: "1.0.0"
  title: Simple Inventory API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /student/{student_id}:
    get:
      summary: gets student
      operationId: getStudentById
      description: |
        Returns a single student
      parameters:
        - in: path
          name: student_id
          description: the uid
          required: true
          schema:
            type: number
            format: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '400':
          description: invalid ID
        '404':
          description: not found
    delete:
      summary: deletes a student
      description: |
        delete a single student
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: the uid
        required: true
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: student deleted
        "400":
          description: bad request
          content:
            text/plain:
              schema:
                type: string
                example: malformed request
        "404":
          description: NOT FOUND
          content:
            text/plain:
              schema:
                type: string
                example: The page you request was not found

  /student:
    post:
      summary: Add a new student
      operationId: addStudent
      description: Adds an item to the system
      responses:
        '200':
          description: created
          content:
            application/json:
              schema:
                type: number
                format: integer
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        description: Student item to add
components:
  schemas:
    Student:
      type: object
      required:
      - first_name
      - last_name
      properties:
        student_id:
          type: integer
        first_name:
          type: string
        last_name:
          type: string
        gradeRecords:
          type: array
          items:
            $ref: '#/components/schemas/GradeRecord'
    GradeRecord:
      type: object
      required:
      - subject_name
      - grade
      properties:
        subject_name:
          type: string
        grade:
          type: number
          minimum: 0.0
          maximum: 10.0