version: '3.3'
services:
  student_service:
    image: jorrit05/student_service
    networks:
      - tutorial
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:pass@mongo:27017/
    ports:
      - "8080:8080"
  mongo:
    image: mongo
    networks:
      - tutorial
    secrets:
      - db_dba_password
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    secrets:
      - db_dba_password
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@mongo:27017/
    networks:
      tutorial:
        aliases:
          - mymongo
secrets:
  db_dba_password:
    external: true

networks:
  tutorial:
    external: true