name: Build Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: jorrit05

defaults:
  run:
    working-directory: 'ass-1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME

    - name: Run Docker
      run: |
        docker-compose up -d
        # Wait for the containers to start
        sleep 5

    - name: Newman CLI (Postman) Action
      uses: anthonyvscode/newman-action@v1.1
      with:
        collection: postman/collection.json 
        # Environment to use
        environment: postman/environment.json
        folder: 'ass-1'
        
        
    #- name: Run API Tests
     # run: |
      #  newman run postman/collection.json -e postman/environment.json

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      run: |
          docker push $REPO_NAME/$IMAGE_NAME
