name: Build Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: jorrit05

defaults:
  run:
    working-directory: 'ass-1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME
    - name: run docker
      run: |
        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
          docker ps && sleep 5


    - name: Run API Tests
      run: |
        docker-compose up
        # Wait for the containers to start. This can be better be done with some aliveness check
        sleep 30s
        newman run postman/collection.json -e postman/environment.json

    - name: Docker Login
      if: always()
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push image to docker hub Container Registry
      if: always()
      run: |
          docker push $REPO_NAME/$IMAGE_NAME
